flowchart LR
%% generated in 0.00s
    subgraph assets__ifuri_ecobar
        assets__ifuri_ecobar__esc["esc"]
        assets__ifuri_ecobar__navHTML["navHTML"]
        assets__ifuri_ecobar__isActive["isActive"]
    end
    assets__ifuri_ecobar__navHTML --> assets__ifuri_ecobar__esc
    assets__ifuri_ecobar__navHTML --> assets__ifuri_ecobar__isActive
